apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: frontend
    team: developer
spec:
  containers:
  - name: succeedcontainer
    image: ubuntu:latest
    ports:
    - containerPort: 80
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 20']